### ISSUE TITLE
No docker Image found

### ISSUE THREAD

**Issue by eelti** [adempiere/adempiere-grpc-all-in-one-docker#11]
When  run docker pull erpya/adempiere-grpc-all-in-one  we got error:
 manifest for erpya/adempiere-grpc-all-in-one:latest not found: manifest unknown: manifest unknown

I take a look in tag and no tag at all 
![NoImage](https://user-images.githubusercontent.com/25960538/101588693-f5764f00-39b4-11eb-85da-c1798916ce6b.png)

**Comment by yamelsenih** [comment]
Hi @eelti can you review it ?

**Comment by eelti** [comment]
I just do the pull now is working.

I will try later build all the container to try this Vue version of Adempiere.
