### ISSUE TITLE
Error when try execute run image container 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere-grpc-all-in-one-docker#19]
docker run -d \
    -it \
    --name adempiere-grpc-all-in-one \
    -p 50059:50059 \
    -e SERVER_PORT=50059 \
    -e SERVICES_ENABLED="access; business; core; dashboarding; dictionary; enrollment; log; ui; workflow; store; pos;" \
    -e SERVER_LOG_LEVEL="WARNING" \
    -e DB_HOST="0.0.0.0" \
    -e DB_PORT="55432" \
    -e DB_NAME="adempiere" \
    -e DB_USER="adempiere" \
    -e DB_PASSWORD="adempiere" \
    -e DB_TYPE="PostgreSQL" \
    erpya/adempiere-grpc-all-in-one

Error Log:

 adempiere-grpc-all-in-one-docker % docker logs 356ce2b7e28a
/bin/sh: [sh,: not found

**Comment by masbenx** [comment]
> docker run -d 
> -it 
> --name adempiere-grpc-all-in-one 
> -p 50059:50059 
> -e SERVER_PORT=50059 
> -e SERVICES_ENABLED="access; business; core; dashboarding; dictionary; enrollment; log; ui; workflow; store; pos;" 
> -e SERVER_LOG_LEVEL="WARNING" 
> -e DB_HOST="0.0.0.0" 
> -e DB_PORT="55432" 
> -e DB_NAME="adempiere" 
> -e DB_USER="adempiere" 
> -e DB_PASSWORD="adempiere" 
> -e DB_TYPE="PostgreSQL" 
> erpya/adempiere-grpc-all-in-one
> 
> Error Log:
> 
> adempiere-grpc-all-in-one-docker % docker logs 356ce2b7e28a
> /bin/sh: [sh,: not found

I still have the same error..
how do you fixed it?

**Comment by e-Evolution** [comment]
@masbenx  this was solve please drop you last docker image and try again
